version: 2.1

orbs:
  node: circleci/node@7.2.1

commands:
  pre:
    description: "Initial setup - checkout, PNPM and restore Turbo cache"
    parameters:

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - restore_cache:
          keys:
            - turbo-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
            - turbo-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
            - turbo-cache-{{ .Environment.CIRCLE_JOB }}-main-
            - turbo-cache-{{ .Environment.CIRCLE_JOB }}-

  post:
    description: "Save Turbo cache"
    steps:
      - save_cache:
          key: turbo-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - .turbo

jobs:
  analyze:
    executor: node/default
    steps:
      - pre
      - run:
          name: Formatting 🖌️ & Linting 🧹 & Spelling 📝
          command: pnpm turbo run format:check lint spell
      - post

  build:
    executor: node/default
    steps:
      - pre
      - run:
          name: Typescript ⌨️ & Build 🏗️
          command: pnpm turbo run typescript build
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - post

  test:
    executor: node/default
    steps:
      - pre
      - run:
          name: Test Raw (Non-Bundle) 🧪
          command: pnpm turbo test:raw
      - post

  test-bundle:
    executor: node/default
    steps:
      - pre
      - attach_workspace:
          at: .
      - run:
          name: Test Bundle ⚗️
          command: pnpm turbo test:bundle
      - post

workflows:
  ci:
    jobs:
      - analyze
      - build
      - test
      - test-bundle:
          requires:
            - build
